POWERLEVEL9K_MODE="nerdfont-complete"

# Prompt Settings
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='\uf0da'

# Prompt Configs
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status dir dir_writable root_indicator vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)

# Dir Truncation
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# VCS CONFIG
POWERLEVEL9K_SHOW_CHANGESET=false

# Time Settings
POWERLEVEL9K_TIME_FORMAT="%D{\uf017 %H:%M:%S}"

# Icons
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_TIME_ICON=''
POWERLEVEL9K_ROOT_ICON="\uF09C"

# Colours
POWERLEVEL9K_OS_ICON_BACKGROUND='white'
POWERLEVEL9K_OS_ICON_FOREGROUND='black'
POWERLEVEL9K_STATUS_OK_BACKGROUND='green'
POWERLEVEL9K_STATUS_OK_FOREGROUND='black'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='black'
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"
