# Aliases
alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
alias sublime="open -a /Applications/Sublime\ Text.app"
alias roadhouse="cd ~/Work/Repos/roadhouse"
alias prodigy="cd ~/Work/Repos/prodigy"
alias repos="cd ~/Work/Repos"
alias sysinfo="~/bin/archey -l"
alias pa="php artisan"
alias n="npm"
alias nr="npm run"
alias proxy="ssh -ND 8888 kussie@kussie.com.au -p 2222"
alias startbe="cd ~/Work/Repos/prodigy/booking-engine-environment; vagrant up"
alias pot='ps -amcwwwxo "command %mem %cpu pid" | grep -v grep | head -16'
alias be="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/prodigy.sh"
alias be:bash="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/prodigy.sh bash"
alias be:robo="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/prodigy.sh robo"
alias be:npm="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/npm.sh"
alias be:func="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/prodigy.sh robo func --host=host.docker.internal --baseUrl=http://fcau.local.prodigy.fcl.cloud"
alias be:jest="cd ~/Work/Repos/prodigy/booking-engine/ && ./bin/prodigy.sh jest -u"
alias be:redis="cd ~/Work/Repos/prodigy/booking-engine/ && docker-compose exec redis redis-cli"
